server:
  port: 8080

spring:
  # datasource:
  #   url: jdbc:sqlserver://xiangmu1-sqlserver.database.windows.net:1433;database=sql-tbl1;user=guanliyuan@xiangmu1-sqlserver;password=Jinzhongmin032!;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  #   username: guanliyuan
  #   password: Jinzhongmin032!
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdatabase
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: demo
